create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id = auth.uid() $$;
create or replace function public.is_adminish() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_role() in ('admin','supervisor'), false) $$;
create or replace function public.is_office_member(p_office uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.office_members m where m.office_id=p_office and m.user_id=auth.uid() and m.active) $$;

alter table public.offices enable row level security;
alter table public.office_members enable row level security;
alter table public.professional_applications enable row level security;
alter table public.parcels enable row level security;
alter table public.parcel_documents enable row level security;
alter table public.document_alignments enable row level security;
alter table public.properties enable row level security;
alter table public.property_media enable row level security;
alter table public.favorites enable row level security;
alter table public.saved_searches enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_parties enable row level security;
alter table public.transaction_events enable row level security;
alter table public.service_requests enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.appointments enable row level security;
alter table public.risk_flags enable row level security;
alter table public.audit_events enable row level security;
alter table public.share_links enable row level security;
alter table public.notifications enable row level security;
alter table public.push_devices enable row level security;

create policy offices_public_read on public.offices for select using (status='approved' or owner_id=auth.uid() or public.is_adminish());
create policy office_members_self_or_admin on public.office_members for select using (user_id=auth.uid() or public.is_office_member(office_id) or public.is_adminish());
create policy professional_owner_read on public.professional_applications for select using (applicant_id=auth.uid() or public.is_adminish());
create policy professional_owner_insert on public.professional_applications for insert with check (applicant_id=auth.uid() and status in ('draft','submitted'));
create policy professional_admin_update on public.professional_applications for update using (public.is_adminish()) with check (public.is_adminish());
create policy parcels_authenticated_read on public.parcels for select to authenticated using (true);
create policy parcel_docs_authorized_read on public.parcel_documents for select using (uploaded_by=auth.uid() or public.is_adminish() or public.current_role() in ('engineer','office'));
create policy parcel_docs_upload on public.parcel_documents for insert with check (uploaded_by=auth.uid() and public.current_role() in ('office','engineer','admin','supervisor'));
create policy properties_public_read on public.properties for select using (status='published' or created_by=auth.uid() or public.is_office_member(office_id) or public.is_adminish());
create policy properties_office_insert on public.properties for insert with check (created_by=auth.uid() and public.is_office_member(office_id) and exists(select 1 from public.offices o where o.id=office_id and o.status='approved'));
create policy properties_office_update on public.properties for update using (public.is_office_member(office_id) or public.is_adminish()) with check (public.is_office_member(office_id) or public.is_adminish());
create policy media_property_access on public.property_media for select using (exists(select 1 from public.properties p where p.id=property_id and (p.status='published' or p.created_by=auth.uid() or public.is_office_member(p.office_id) or public.is_adminish())));
create policy favorites_self on public.favorites for all using (user_id=auth.uid()) with check(user_id=auth.uid());
create policy saved_searches_self on public.saved_searches for all using (user_id=auth.uid()) with check(user_id=auth.uid());
create policy service_self_read on public.service_requests for select using (user_id=auth.uid() or public.is_adminish());
create policy service_self_insert on public.service_requests for insert with check (user_id=auth.uid());
create policy conversation_member_read on public.conversations for select using (exists(select 1 from public.conversation_members cm where cm.conversation_id=id and cm.user_id=auth.uid()) or public.is_adminish());
create policy messages_member_read on public.messages for select using (exists(select 1 from public.conversation_members cm where cm.conversation_id=messages.conversation_id and cm.user_id=auth.uid()) or public.is_adminish());
create policy messages_member_insert on public.messages for insert with check (sender_id=auth.uid() and exists(select 1 from public.conversation_members cm where cm.conversation_id=messages.conversation_id and cm.user_id=auth.uid()));
create policy notifications_self on public.notifications for select using(user_id=auth.uid());
create policy push_devices_self on public.push_devices for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy audit_admin_read on public.audit_events for select using(public.is_adminish());
