import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';

const root=process.cwd(); const out=path.join(root,'.tmp-domain'); fs.rmSync(out,{recursive:true,force:true}); fs.mkdirSync(out,{recursive:true});
const files=['types/domain.ts','domain/permissions.ts','domain/professionalApproval.ts','domain/media.ts','domain/searchFilters.ts','domain/notifications.ts','domain/rateLimit.ts','domain/risk.ts','domain/alignment.ts','domain/transactions.ts','domain/report.ts','domain/officeMembers.ts','domain/propertyDraft.ts','domain/savedSearch.ts','domain/serviceWorkflow.ts','domain/notificationQueue.ts','domain/transactionHistory.ts','domain/deepLinks.ts','domain/offlineSync.ts','domain/mapSourceSecurity.ts'];
for(const rel of files){ const src=path.join(root,'src',rel); const js=ts.transpileModule(fs.readFileSync(src,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText; const dest=path.join(out,rel.replace(/\.ts$/,'.mjs')); fs.mkdirSync(path.dirname(dest),{recursive:true}); let fixed=js.replace(/from ['"](\.\.?\/[^'"]+)['"]/g,(m,p)=>`from '${p}.mjs'`); fs.writeFileSync(dest,fixed); }
const imp=async(rel)=>import(pathToFileURL(path.join(out,rel)).href+`?t=${Date.now()}`);
const permissions=await imp('domain/permissions.mjs'); assert.equal(permissions.can('office','property.publish'),true); assert.equal(permissions.can('citizen','property.publish'),false);
const approval=await imp('domain/professionalApproval.mjs'); const a={id:'1',applicantId:'u',type:'engineer',status:'under_review',licenseNumber:'x',issuingAuthority:'y',governorates:['الأنبار']}; assert.equal(approval.transitionProfessional(a,'approved','admin').status,'approved'); assert.throws(()=>approval.transitionProfessional(a,'rejected','citizen','x'));
const media=await imp('domain/media.mjs'); const items=[{id:'a',kind:'image',storagePath:'a.jpg',mimeType:'image/jpeg',sizeBytes:1,sortOrder:0,isCover:true},{id:'b',kind:'image',storagePath:'b.jpg',mimeType:'image/jpeg',sizeBytes:1,sortOrder:1,isCover:false}]; assert.deepEqual(media.reorderMedia(items,['b','a']).map(x=>x.id),['b','a']); assert.equal(media.setCoverMedia(items,'b')[1].isCover,true);
const search=await imp('domain/searchFilters.mjs'); assert.equal(search.matchesProperty({id:'1',governorate:'الأنبار',district:'الرمادي',type:'دار',purpose:'sale',price:100,areaSqm:200,text:'منزل جميل'},{query:'الانبار',minArea:100}),true);
const risk=await imp('domain/risk.mjs'); const flags=risk.evaluateRisks({declaredAreaSqm:100,mappedAreaSqm:120,documentParcelNumber:'1',listingParcelNumber:'2'}); assert.equal(flags.some(f=>f.code==='parcel_number_mismatch'),true); assert.equal(risk.riskScore(flags)>0,true);
const align=await imp('domain/alignment.mjs'); const pairs=[{source:{lat:0,lng:0},target:{lat:1,lng:2}},{source:{lat:0,lng:1},target:{lat:1,lng:3}},{source:{lat:1,lng:0},target:{lat:2,lng:2}}]; const t=align.solveAffine(pairs); const p=align.applyAffine(t,{lat:2,lng:3}); assert.ok(Math.abs(p.lat-3)<1e-9 && Math.abs(p.lng-5)<1e-9);
const rate=await imp('domain/rateLimit.mjs'); assert.equal(rate.isRateLimited([{atMs:900},{atMs:950}],1000,200,2),true);
const tx=await imp('domain/transactions.mjs'); assert.equal(tx.canMoveTransaction('opened','documents'),true); assert.equal(tx.canMoveTransaction('completed','opened'),false); assert.equal(tx.makeTrackingCode(()=>0).length,10);
const notify=await imp('domain/notifications.mjs'); assert.deepEqual(notify.safeChannels(['push','email','in_app'],false,true,false),['email','in_app']);

const office=await imp('domain/officeMembers.mjs'); assert.equal(office.officeMemberCan('manager','property.publish'),true); assert.equal(office.officeMemberCan('agent','property.publish'),false); assert.equal(office.canAssignOfficeRole('manager','manager'),false);
const draft=await imp('domain/propertyDraft.mjs'); const ready={title:'دار مميزة',propertyType:'دار',purpose:'sale',price:100,areaSqm:200,governorate:'الأنبار',mediaCount:2,coverImageCount:1,parcelLinked:true,unresolvedHighRiskCount:0,officeApproved:true}; assert.equal(draft.canPublishProperty(ready),true); assert.equal(draft.canPublishProperty({...ready,unresolvedHighRiskCount:1}),false);
const saved=await imp('domain/savedSearch.mjs'); const ms=saved.evaluateSavedSearches({id:'p1',governorate:'الأنبار',district:'الرمادي',type:'دار',purpose:'sale',price:100,areaSqm:200},[{id:'s1',userId:'u1',enabled:true,filters:{governorate:'الأنبار',minArea:150}}]); assert.equal(ms.length,1); assert.equal(ms[0].dedupeKey,'saved_search:s1:property:p1');
const service=await imp('domain/serviceWorkflow.mjs'); assert.equal(service.canMoveServiceRequest('submitted','under_review'),true); assert.equal(service.canMoveServiceRequest('closed','approved'),false); assert.throws(()=>service.requireServiceDecisionNote('rejected'));
const queue=await imp('domain/notificationQueue.mjs'); assert.equal(queue.canClaimNotificationJob({status:'pending',attempts:0,maxAttempts:5,nextAttemptAtMs:100},100),true); const retry=queue.nextNotificationJobAfterFailure({status:'processing',attempts:0,maxAttempts:3,nextAttemptAtMs:0},1000); assert.equal(retry.status,'pending'); assert.equal(retry.attempts,1); assert.ok(retry.nextAttemptAtMs>1000);
const history=await imp('domain/transactionHistory.mjs'); const vh=history.visibleTransactionHistory([{status:'documents',visibleToClient:true,createdAtIso:'2026-01-02T00:00:00Z'},{status:'opened',visibleToClient:true,createdAtIso:'2026-01-01T00:00:00Z'},{status:'legal_review',visibleToClient:false,createdAtIso:'2026-01-03T00:00:00Z'}]); assert.deepEqual(vh.map(x=>x.status),['opened','documents']); assert.equal(history.transactionProgress('completed'),100);
const links=await imp('domain/deepLinks.mjs'); assert.equal(links.routeForTarget(links.parseNotificationData({topic:'saved_search',entityId:'p1'})),'/property/p1');
const offline=await imp('domain/offlineSync.mjs'); assert.equal(offline.decideConflict({baseRevision:3,remoteRevision:3,operation:'update'}),'apply'); assert.equal(offline.decideConflict({baseRevision:3,remoteRevision:4,operation:'update'}),'conflict');
const maps=await imp('domain/mapSourceSecurity.mjs'); assert.deepEqual(maps.validateMapSourceEndpoint('http://127.0.0.1/x').sort(),['https_required','private_host_blocked'].sort()); assert.deepEqual(maps.validateMapSourceEndpoint('https://maps.example.com/wms'),[]);
console.log('test:domain: ok (permissions, approvals, office roles, media, property readiness, search, saved searches, risk, alignment, rate-limit, transactions, notifications, service workflow, notification queue, transaction history, deep links, offline conflicts, map source security)');
