-- Cover the foreign-key paths used heavily by feeds, office dashboards, messages and background jobs.
create index if not exists appointments_office_idx on public.appointments(office_id, starts_at);
create index if not exists appointments_property_idx on public.appointments(property_id);
create index if not exists appointments_requester_idx on public.appointments(requester_id, created_at);
create index if not exists audit_events_actor_idx on public.audit_events(actor_id, created_at desc);
create index if not exists conversation_members_user_idx on public.conversation_members(user_id, conversation_id);
create index if not exists conversations_office_idx on public.conversations(office_id, created_at desc);
create index if not exists conversations_property_idx on public.conversations(property_id, created_at desc);
create index if not exists document_alignments_document_idx on public.document_alignments(document_id, created_at desc);
create index if not exists document_alignments_approved_by_idx on public.document_alignments(approved_by);
create index if not exists favorites_property_idx on public.favorites(property_id);
create index if not exists messages_conversation_idx on public.messages(conversation_id, created_at);
create index if not exists messages_sender_idx on public.messages(sender_id, created_at desc);
create index if not exists notification_jobs_user_idx on public.notification_jobs(user_id, created_at desc);
create index if not exists office_invites_office_idx on public.office_member_invitations(office_id, created_at desc);
create index if not exists office_invites_creator_idx on public.office_member_invitations(created_by, created_at desc);
create index if not exists office_members_user_idx on public.office_members(user_id, active);
create index if not exists offices_owner_idx on public.offices(owner_id, status);
create index if not exists parcel_documents_parcel_idx on public.parcel_documents(parcel_id, created_at desc);
create index if not exists parcel_documents_uploader_idx on public.parcel_documents(uploaded_by, created_at desc);
create index if not exists parcels_source_idx on public.parcels(source_id);
create index if not exists processing_jobs_document_idx on public.processing_jobs(document_id, status);
create index if not exists professional_applicant_idx on public.professional_applications(applicant_id, status);
create index if not exists professional_reviewer_idx on public.professional_applications(reviewer_id, reviewed_at desc);
create index if not exists properties_office_idx on public.properties(office_id, status, created_at desc);
create index if not exists properties_creator_idx on public.properties(created_by, created_at desc);
create index if not exists properties_parcel_idx on public.properties(parcel_id);
create index if not exists property_media_uploader_idx on public.property_media(uploaded_by, created_at desc);
create index if not exists property_reports_property_idx on public.property_reports(property_id, generated_at desc);
create index if not exists property_reports_requester_idx on public.property_reports(requested_by, generated_at desc);
create index if not exists push_devices_user_idx on public.push_devices(user_id, enabled);
create index if not exists risk_flags_property_idx on public.risk_flags(property_id, resolved_at, severity);
create index if not exists risk_flags_document_idx on public.risk_flags(document_id);
create index if not exists risk_flags_resolver_idx on public.risk_flags(resolved_by);
create index if not exists saved_searches_user_idx on public.saved_searches(user_id, enabled);
create index if not exists service_events_actor_idx on public.service_request_events(actor_id, created_at desc);
create index if not exists service_requests_user_idx on public.service_requests(user_id, created_at desc);
create index if not exists service_requests_assignee_idx on public.service_requests(assigned_to, status, updated_at desc);
create index if not exists share_links_creator_idx on public.share_links(created_by, created_at desc);
create index if not exists transaction_events_creator_idx on public.transaction_events(created_by, created_at desc);
create index if not exists transactions_creator_idx on public.transactions(created_by, created_at desc);
create index if not exists transactions_property_idx on public.transactions(property_id, created_at desc);
